name: ecommerce_project

packages:
  - app/**
  - feature/** # This will include all packages in the feature directory

command:
  bootstrap:
    usePubspecOverrides: true
    runPubGetInParallel: false

sdk:
  path: .fvm/flutter_sdk

scripts:
  analyze:
    run: melos exec -- flutter analyze .
  test:
    run: melos exec -- flutter test

dependencies:
  flutter:
    sdk: flutter
    go_router: ^14.2.0
    provider: ^6.1.2
    dio: ^5.4.3+1
    flow_builder: ^0.1.0
    freezed_annotation: ^2.4.1

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0
    build_runner: ^2.4.11
    freezed: ^2.5.3

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"